version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres@db/code_review_bot
      - GITHUB_TOKEN
      - SLACK_TOKEN
      - SLACK_CHANNEL
      - SLACK_CLIENT_ID
      - SLACK_CLIENT_SECRET
      - APP_SECRET
    depends_on:
      - db

