FROM rust:1.32

WORKDIR /app
RUN USER=root cargo init
COPY Cargo.toml .
RUN cargo build --release

RUN cargo install diesel_cli

COPY src src
RUN cargo install --path .
COPY resources resources
COPY migrations migrations

CMD ["code_review_bot", "-p", "80"]
