version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres@db/code_review_bot
      - GITHUB_TOKEN
      - SLACK_TOKEN
      - SLACK_CHANNEL
    depends_on:
      - db

